description: MNIST digit classifier MLP

type: classifier

randomInit: True

graph:

 - activation:   conv2d
   n_in:         784
   n_filters:    1
   filter_width: 5
   n_out:        576
   dropout:      0.5

 - activation: tanh
   n_in:       576
   n_out:      300
   dropout:    0.2

 - activation: tanh
   n_in:       300
   n_out:      300
   dropout:    0.2

 - activation: softmax
   n_in:       300
   n_out:      10
   dropout:    0.2
