description: MNIST digit classifier MLP

type: classification

supervised-cost:
  type: negative-log-likelihood
  name: class-out

type: classification

graph:

 - activation: tanh
   n_in:       784
   n_out:      300
   dropout:    0.0
   name: layer1

 - activation: tanh
   n_in:       300
   n_out:      300
   dropout:    0.0
   name: layer2

 - activation: softmax
   n_in:       300
   n_out:      10
   dropout:    0.0
   name: class-out
